### ISSUE TITLE
php build fails

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#418] opened 2016-05-01 23:50 UTC
Hi,
I went through all the steps in the readme, from cloning the repo, right up to running "butch install world", for x86_64.

It completed, except for two build fails, php and mysql.

Here is the build log for php:
[build_php.log.txt](https://github.com/sabotage-linux/sabotage/files/244399/build_php.log.txt)

**Comment by liwakura** [comment] 2016-10-30 23:10
Could not reproduce as of Oct 2016. Probably fixed with f6e67c72.

**Comment by rofl0r** [comment] 2016-10-31 18:15
good catch. closing this.

**Closed by rofl0r** 2016-10-31 18:15 UTC
